Full Re-Design
smelt-modding/smelt-modding.github.io pull request #4
Opened 2017-10-08 14:56 UTC by VutonDesign

### Why are you making this request?
The site looked a bit old and plain, So I've taken the css from my old site and customized it to fit the style of Smelt.

### What issue does this reference/resolve?
#3

2017-10-08 22:40 UTC, Kenny2github requested changes
Looks great! Though your design is on point (and judging from the screenshots, it’s looking a lot better), your code style needs a bit of work. Would you mind making consistent indentation? Thanks.

2017-10-08 22:40 UTC, Kenny2github commented on stylesheet.css
> +* {
Nice, thanks for this

2017-10-08 22:40 UTC, Kenny2github commented on index.html
> +					<div class="boxes">
This is some weird indentation - would you mind making everything consistent? I.e.
```html
    </ol>
</div>
<div class="boxes">
```

2017-10-08 22:40 UTC, Kenny2github commented on index.html
> +	</center>
Here, too - your indentation generally needs work.

2017-10-09 07:24 UTC, VutonDesign commented
@Kenny2github I'll work on all of this 👍

2017-10-09 07:38 UTC, VutonDesign commented
Done, How's that?

2017-10-09 14:12 UTC, Kenny2github approved these changes
Looks better! I’m not going to be too nit picky about indentation (I can solve it myself) so I’ll merge this now.

2017-10-09 14:13 UTC, merged